### PR TITLE
Add calculation of total energy to postprocessing

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
This PR adds the calculation of the total energy to the postprocessing.
The total energy is a usefull diagnostic to see if a model is in thermal equilibrium.

This PR also fixes the calculation of the geometrical height. For this we need to still need to update the netcdf processed files in the test, because they are wrong as well.

- [x] update netcdf file on zenodo

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
Something is wrong here and it looks to me as if this is related to xmitgcm somehow. Doesn't seem to be related to this PR.

I will check this tomorrow.

**Comment by AaronDavidSchneider** [comment]
units are also still wrong...

**Comment by AaronDavidSchneider** [comment]
@robinbaeyens:
Could you check the calculation and let me know if this is physically correct?

I think the magnitude of the outcoming values seems fine.

**Review by Kiefersv — APPROVED** [review]

**Comment by AaronDavidSchneider** [comment]
@robinbaeyens: Do you still want to look at this or should I merge this? @Kiefersv thinks that it should be correct (we talked about this last week).

**Comment by robinbaeyens** [comment]
@AaronDavidSchneider No, you can just go ahead with the pull. I don't have much time nowadays and if you 2 think it's fine, it will be!

**Pull request merged**
