### PR TITLE
add option to calculate dayside and nightside averages

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
Hi @robinbaeyens and @Kiefersv,

I added an option to calculate dayside and nightside averages, which might be useful sometimes. I also added the option to call the average function with any dataarray that might be compatible.

Here are some examples:

```py
tools.add_horizontal_average('T', 'T_g', tag='HD2')
tools.add_horizontal_average('T', 'T_g', tag='HD2', part='all')  # identical to above (global by default)
tools.add_horizontal_average('T', 'T_night', tag='HD2', part='night')  # nightside average around -180,0
tools.add_horizontal_average('T', 'T_day', tag='HD2', part='day')       # dayside average around 0,0
tools.add_horizontal_average(ds.T, 'T_day', tag='HD2', part='day')  # is the same as above
```

Of course, this makes the assumption that dayside == abs(lon) < 90. However, since this should be the default for most people and its documented in the docstring, I think it should be fine. 

What do you guys think?

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
I also added morning and evening terminator regions (around +-10 deg of +-90 deg lon). I hope its the correct way and not the other way around :D

**Comment by AaronDavidSchneider** [comment]
Note for better understanding of the way this PR operates in calculating the individual averages:
The averages are calculated by setting the areas of the parts that should not be included in the average to 0. This should be possible since the average is an area weighted average. Setting the area to zero for those parts that are not included in the average is therefore as to not include this part for the average.

**Review by robinbaeyens — APPROVED** [review]
Hey Aaron, this looks good to me, and I can definitely see these partial averages getting some use!

I am wondering, however, if it would not be even better to generalize it more. Since the day/night sides and terminators are all 'special' cases of a general local average. You could imagine something like specifying `m_add_horizontal_average(... , restrict_lon=[-100, -80], restrict_lat=[-90, 90] , ...)`, with the hemispheric and terminator averages being a special case of `restrict_lon` and `restrict_lat`. What do you think?

**Comment by AaronDavidSchneider** [comment]
> Hey Aaron, this looks good to me, and I can definitely see these partial averages getting some use!
> 
> I am wondering, however, if it would not be even better to generalize it more. Since the day/night sides and terminators are all 'special' cases of a general local average. You could imagine something like specifying `m_add_horizontal_average(... , restrict_lon=[-100, -80], restrict_lat=[-90, 90] , ...)`, with the hemispheric and terminator averages being a special case of `restrict_lon` and `restrict_lat`. What do you think?

Thanks for your feedback @robinbaeyens! I agree that it would be less restrictive to have something like `restrict_lat` and `restrict_lon`.

I am thinking that the most convenient way would be to have both, where you can use part also with a dictionary. I will update the PR accoringly.

**Comment by AaronDavidSchneider** [comment]
This new version adds the generalized mask that @robinbaeyens suggested. I couldnt find a way that would bring all of this easier together. One of the reasons being that night is just the oppisite of day and there is no mask for night that can be used that I could think of that could have been specified via the suggested format.

What do you think @robinbaeyens? Also is the naming of terminators correct? I always get confused...

**Review by robinbaeyens — APPROVED** [review]
Yup, that seems to do the trick. Thanks for the implementation! 
The naming of the terminators looks alright as well ;)

**Comment by AaronDavidSchneider** [comment]
Ok. I am going to merge this, since its not introducing any breaking change. If @Kiefersv wants to have an additional look at it, we can continue the conversation here.

**Pull request merged**
