### PR TITLE
Theta, rcb and angular momentum

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
This PR is about to calculate the above mentionened quantities.

Todo:
- [x] propagate to gcmt class
- [x] add tests
- [x] add documentation

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
Test error:
```

>       if c["Z"].argmax() != 0:
4799
E       AttributeError: 'str' object has no attribute 'argmax'
```

In is the data basic. Will fix later.

**Review by AaronDavidSchneider — COMMENTED** [review]
Should be done now

**Comment by AaronDavidSchneider** [comment]
Hi @Kiefersv, @robinbaeyens,

this PR is ready now. I added the calculation of the potential temperature, the rcb location and the total angular momentum. I'd be happy to get a review on it.

Cheers
Aaron

**Review by robinbaeyens — APPROVED** [review]
Looks good to me. Go for it!

**Pull request merged**
